config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'home' => 'home#index'

  get 'logout', to: 'sessions#destroy', as: :logout
  get 'fake' => 'sessions#fake'

  resources :messages, only: %i[new create]

  resources :rooms, only: %i[index new create show]

  match '/auth/steam/callback' => 'sessions#create', via: %i[get post]
  root 'home#index'
end

app/models/application_record.rb
# frozen_string_literal: true

# rubocop:disable Style/Documentation
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end
# rubocop:enable Style/Documentation

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :player
  belongs_to :room
  validates :content,
            presence: true,
            length: { maximum: 300 }
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :messages
  has_many :presences
  has_many :rooms, through: :presences

  def self.from_omniauth(auth)
    info = auth['info']
    player = find_or_initialize_by(uid: auth['uid'])
    player.nickname = info['nickname']
    player.avatar_url = info['image']
    player.profile_url = info['urls']['Profile']
    player.save!
    player
  end

  def presence_by_room(id)
    if presences.find_by(room_id: id).nil?
      rooms << Room.find(id)
    end

    presences.find_by(room_id: id)
  end

  def set_online_status_by_room(status, id)
    presence_by_room(id).update(online: status)
  end
end

app/models/presence.rb
class Presence < ApplicationRecord
  belongs_to :player
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :presences
  has_many :messages
  has_many :players, through: :presences
  validates :name,
            presence: true,
            length: { maximum: 60 }
  validates :limit,
            presence: true

  def online_players
    Player.joins(:presences).where('presences.room_id': id, 'presences.online': true)
  end

  def is_full?
	online_players.length == limit ? true : false
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  private

  def current_player
    return nil unless session[:player_id]

    player = Player.find_by(id: session[:player_id])

    @current_player = player
  end

  helper_method :current_player
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# Home Page Controller
class HomeController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
  end

  def create
    @message = Message.create(msg_params)
    @message.player = current_player

    return unless @message.save

    ActionCable.server.broadcast "room_#{@message.room.id}_channel", content: @message.content, player: @message.player
  end

  private

  def msg_params
    params.require(:message).permit(:content, :room_id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[show]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.where(visible: true).all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @room = Room.find(params[:id])
    if @room.is_full? or current_player.presence_by_room(@room.id).online == true
      redirect_to "/"
    end
    @message = Message.new room: @room
    @messages = Message.where(room: @room).includes(:player).last(10)
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)
    @room.visible = true

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:name, :limit)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # omniayth-steam does not provide the CSRF token
  skip_before_action :verify_authenticity_token, only: :create

  def create
    @player = Player.from_omniauth request.env['omniauth.auth']
    session[:player_id] = @player.id
    cookies.encrypted[:player_id] = @player.id
    redirect_to root_path
  end

  def fake
    @player = Player.create(
      uid: Faker::Internet.uuid,
      nickname: Faker::Name.first_name,
      avatar_url: Faker::Avatar.image,
      profile_url: 'https://steamcommunity.com/id/lol'
    )
    session[:player_id] = @player.id
    cookies.encrypted[:player_id] = @player.id
    redirect_to root_path
  end

  def destroy
    if current_player
      player_id = current_player.id
      session.delete :player_id
      cookies.delete :player_id
    end
    redirect_to root_path
    ActionCable.server.remote_connections.where(current_player: player_id).disconnect
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper # rubocop:disable Style/Documentation
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper # rubocop:disable Style/Documentation
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/home/_chat_box.html.slim
body data-controller="chat"

.card.bg-dark
  .card-header Chat
  .card-body
    .row
      .col-lg-9
        ul#chat.chat
          - @messages.each do |message|
            li
              - if message.player.uid == current_player.uid
                span#my_name = "#{message.player.nickname}: "
              - else
                span#name = "#{message.player.nickname}: "
              = message.content
            / li = "#{message.player.nickname}: #{message.content}"
      .col-lg-3
        ul#users.users
          | loading
    hr
    = form_for( @message , remote: true, html: {class: 'input-group'}) do |f|
      = f.text_field (:content), class: 'form-control input-sm', placeholder: 'Message'
      = f.submit style: 'border-radius: 0 0.2rem 0.2rem 0', class: 'btn btn-primary btn-sm'

app/views/home/index.html.slim
- if current_player
  p hello
- else
  p faça login

app/views/layouts/_footer.html.slim
footer.page-footer.font-small.blue
  .footer-copyright.text-center.py-3
    | © 2018 Copyright:
    a href="https://mdbootstrap.com/education/bootstrap/"  MDBootstrap.com

app/views/layouts/_nav_bar.html.slim
div.bg-dark
  nav.navbar.navbar-dark.bg-dark.navbar-expand-sm
    = link_to(root_path, class: 'navbar-brand') do
      | BattleBuff
    button.navbar-toggler [aria-controls="navbarNav"
                          aria-expanded="false"
                          aria-label=("Toggle navigation")
                          data-target="#navbar-list-2"
                          data-toggle="collapse"
                          type="button"]
      span.navbar-toggler-icon
    #navbar-list-2.collapse.navbar-collapse
      ul.navbar-nav.mr-auto
        li.nav-item
          = link_to "Salas", Room, class: 'nav-link'

      ul.navbar-nav.ml-auto
        li.nav-item
          = link_to "Login-fake", "/fake", class: 'nav-link'
        li.nav-item
          = link_to "Login", "/auth/steam", class: 'nav-link'

app/views/layouts/_side_bar.slim
.well.sidebar-nav
  - if current_player
    span#player_uid style="display: none"
      = current_player.uid
    div.avatarcontainer
      | #{image_tag current_player.avatar_url, class: 'avatar'}
    ul.nav.nav-list style="display: block;"
      li
        | Name: #{current_player.nickname}
      li
        | ID: #{current_player.uid}
      li= link_to "Logout", logout_path
  - else
    li Not logged in.

app/views/layouts/application.html copy.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Battlebuff" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Battlebuff', root_path, class: 'navbar-brand' %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <!-- <li><%= link_to "Link1", "/path1"  %></li> -->
          </ul>
          <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Login", "/auth/steam", class: 'navbar-brand' %></li>
            </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Steam profile</h3>
            <ul class="nav nav-list">
              <% if current_player %>
              <li>avatar: <%= image_tag current_player.avatar_url %></li>
              <li>nickname: <%= current_player.nickname %></li>
              <li>steam_id: <%= current_player.uid %></li>
              <li><%= link_to "Logout", logout_path %></li>
              <% else%>
              <li>Not logged in.</li>
              <% end %>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="col-lg-9">
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2019</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Battlebuff" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Battlebuff', root_path, class: 'navbar-brand' %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <!-- <li><%= link_to "Link1", "/path1"  %></li> -->
          </ul>
          <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Login", "/auth/steam", class: 'navbar-brand' %></li>
            </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Steam profile</h3>
            <ul class="nav nav-list">
              <% if current_player %>
              <li>avatar: <%= image_tag current_player.avatar_url %></li>
              <li>nickname: <%= current_player.nickname %></li>
              <li>steam_id: <%= current_player.uid %></li>
              <li><%= link_to "Logout", logout_path %></li>
              <% else%>
              <li>Not logged in.</li>
              <% end %>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2019</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/application.html.slim
doctype html
html lang="en" 
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    meta charset="utf-8" /
    meta content="IE=Edge,chrome=1" http-equiv="X-UA-Compatible" /
    meta content="width=device-width, initial-scale=1.0" name="viewport" /
    title= content_for?(:title) ? yield(:title) : "Battlebuff"
    = csrf_meta_tags
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render "layouts/nav_bar"
    .container style="margin-top:30px"
      .row
        .col-lg-3
          = render "layouts/side_bar"
        .col-lg-9
          = yield
    = render "layouts/footer"

app/views/rooms/_chat_box.html.slim
body data-controller="chat"

.card.bg-dark
  .card-header = "Chat room: #{@room.name}"
  .card-body
    .row
      .col-lg-9
        ul#chat.chat
          - @messages.each do |message|
            li
              - if message.player.uid == current_player.uid
                span#my_name = "#{message.player.nickname} : "
              - else
                span#name = "#{message.player.nickname} : "
              = message.content
            / li = "#{message.player.nickname}: #{message.content}"
      .col-lg-3
        ul#users.users
          | loading
    hr
    = form_for( @message , remote: true, html: {class: 'input-group'}) do |f|
      = f.text_field (:content), class: 'form-control input-sm', placeholder: 'Message'
      = f.submit style: 'border-radius: 0 0.2rem 0.2rem 0', class: 'btn btn-primary btn-sm'
      = f.hidden_field :room_id

app/views/rooms/_form.html.slim
= form_for @room do |f|
  - if @room.errors.any?
    #error_explanation
      h2 = "#{pluralize(@room.errors.count, "error")} prohibited this rooom from being saved:"
      ul
        - @room.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :limit
    = f.number_field :limit
  .actions = f.submit

app/views/rooms/index.html.slim
h1 Listing rooms

table
  thead
    tr
      th Name
      th Slots
      th
  tbody
    - @rooms.each do |room|
      tr
        td = room.name
        td = "#{room.limit}/#{room.online_players.length}"
        td = link_to 'Show', room

br

= link_to 'New Room', new_room_path

br

button onclick="location.reload();" refresh

app/views/rooms/new.html.slim
h1 New room

== render 'form'

= link_to 'Back', rooms_path

app/views/rooms/show.html.slim
/ technical adjust :)
p#room_id style="display: none" = @room.id

== render "chat_box"

=< link_to 'Back', rooms_path